version: '3.8'

services:
  # FastAPI app
  miq:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_URI=postgresql://postgres:password@miq_db:5432/miq_db
      # - SECRET_KEY
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_SECONDS=86400
    depends_on:
      - miq_db
    networks:
      - app-network

  # postgre DB
  miq_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: miq_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - miq_db_data:/var/lib/postgresql/data
  
  # Redis cache
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Prometheus + Garafana monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network
  
  # CloudBeaver for DB access
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: always
    ports:
      - "8978:8978"
    volumes: 
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      -  app-network

networks:
  app-network:

volumes:
  miq_db_data:
  cloudbeaver:
