name: CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

permissions:
  contents: read

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PSW: ${{ secrets.DB_PSW }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PORT: 5432
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: 6379
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_SECONDS: 86400
  RATE_LIMIT_REQUESTS: 60

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.1"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Test with pytest
      run: |
        pipenv run pytest tests
